schema:
  format:
    openapi: "3.0.0"
  service_input_type: "LoadBalancedServiceInput"
  pipeline_input_type: "PipelineInputs"

  types:
    LoadBalancedServiceInput:
      type: object
      description: "Input properties for a loadbalanced Fargate service"
      properties:
        port:
          type: number
          description: "The port to route traffic to"
          default: 8080
          minimum: 0
          maximum: 65535
        health_check_interval_seconds:
          type: number
          description: "Health check interval in seconds"
          default: 90
          minimum: 2
          maximum: 300
        health_check_timeout_seconds:
          type: number
          description: "Healt check timout in seconds"
          default: 60
          minimum: 2
          maximum: 120
        health_check_success_code:
          type: string
          description: "HTTP Success code for healt check"
          default: "200-499"
        desired_count:
          type: number
          description: "The default number of Fargate tasks you want running"
          default: 1
          minimum: 1
        task_size:
          type: string
          description: "The size of the task you want to run"
          enum: ["x-small", "small", "medium", "large", "x-large"]
          default: "x-small"
        image:
          type: string
          description: "The name/url of the container image"
          default: "public.ecr.aws/z9d2n7e1/nginx:1.19.5"
          minLength: 1
          maxLength: 200
        service_discovery_name:
          type: string
          description: "The name of the service to register in service discovery"
          minLength: 3
          maxLength: 24
      required:
        - service_discovery_name

    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        dockerfile:
          type: string
          description: "The location of the Dockerfile to build"
          default: "Dockerfile"
          minLength: 1
          maxLength: 100
        unit_test_command:
          type: string
          description: "The command to run to unit test the application code"
          default: "./gradlew test"
          minLength: 1
          maxLength: 200
        shared_ecr_repo:
          type: string
          description: "Shared ECR repo to get access to"
          default: openjdk-11-jre
