apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: tink3-sandbox
  region: us-west-1
  version: "1.20"
managedNodeGroups:
- name: primary
  instanceType: t2.small
  minSize: 3
  maxSize: 6
  spot: true
